# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives

In this lab you will: 

- Find the shape of vectors and matrices 
- Access and manipulate individual scalar components of a matrix 
- Create vectors and matrices using Numpy and Python

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [3]:
# Code here
a = np.array([[1402, 191],[1371, 821],[949, 1437],[147, 1448]])
b = np.array([[1,2,3],[4,5,6]])

## 2. Print the dimensions of $A$ and $B$ 

In [4]:
# Code here
print(a.shape, b.shape)

(4, 2) (2, 3)


## 3. Print elements from $A$

Print the following elements from $A$: 

* First row and first column
* First row and second column
* Third row and second column
* Fourth row and first column

In [16]:
# Code here
print('first row, first col',a[0,0])
print('first row and second col', a[0,1])
print('third row and second col', a[2,1])
print('fourth row and first col', a[3,0])

first row, first col 1402
first row and second col 191
third row and second col 1437
fourth row and first col 147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10 

In [23]:
# Code here

arr = np.zeros((3,3))


for i in range (0,3):
    for j in range(0,3):
        arr[i,j] = np.random.randint(low = 1,high = 11)
        
print(arr)

[[5. 9. 4.]
 [9. 7. 9.]
 [6. 9. 2.]]


## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in Numpy 
* Print the results

In [25]:
# Code here
def build_arr(rows,cols):
    arr = np.zeros((rows,cols))


    for i in range (0,rows):
        for j in range(0,cols):
            arr[i,j] = np.random.randint(low = 1,high = 11)
    
    return arr

a = build_arr(4,4)
b = buil_arr(4,4)

print(a,b)

NameError: name 'buil_arr' is not defined

## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in Numpy. We shall now move forward to learning more complex operations including dot products and matrix inversions.  